security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_TEST_SYSTEM_USER ]

    providers:
        sonata_test:
            memory:
                users:
                    admin: { password: admin, roles: 'ROLE_SUPER_ADMIN' }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern:      /admin(.*)
            form_login:
                provider:       sonata_test
                default_target_path: /admin/dashboard
                always_use_default_target_path: true
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   /admin/login
            logout:
                path:   /admin/logout
                target: /admin/login
            anonymous:    true
        default:
            anonymous: ~

    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin/.*, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }