suncat_admin_page_board:
    page_boards:
        news_detail:
            blocks:
                -
                    position: left
                    type: suncat_admin_page_board.admin.block.admin_show
                    settings:
                        title: News detail (admin show)
                        sonata_admin_code: suncat_admin.admin.news
                -
                    position: left
                    type: suncat_admin.admin.block.news_detail
                    settings:
                        title: News detail (manual)
                -
                    position: right
                    type: suncat_admin.admin.block.news_comments
                    settings:
                        title: News comments
                -
                    position: right
                    type: suncat_admin.admin.block.news_tags
                    settings:
                        title: News tags
            route:
                name: admin_suncat_admin_news_board
                path: /suncat/admin/news/{id}/board
                requirements:
                    id:  \d+